### ISSUE TITLE
Guidance Request: How to use micro-aprs on the ESP32

### ISSUE THREAD

**Issue by nitricware** [stephanelsmith/micro-aprs#1]
Hy,

I find the repo very promising for what I try to achieve:

1. have weather sensors and a SA818-V module connected to an ESP32 running Micropython
2. send an AFSK-encoded APRS packet with micro-aprs via the ESP32's DAC to the SA818-V.
 
If understood correctly: Since the ESP32 would take an input, transform that in a AX.25 packet and generate an AFSK signal, the ESP32 would be the TNC. No other components required.

Given the high quality of the existing tutorials in this repo, I was hoping to find more information on how to use micro-aprs directly on the ESP32. Since there is no pip-package available this is not trivial, especially for someone not too familiar with Python.

- Should I just place the contents of the `src` directory in my project structure?
- What should I do with the c_modules?
- How would I run `echo "KI5TOF>APRS:>hello world!" | micropython aprs_mod.py | sox -t raw -b 16 -e signed-integer -c 1 -v 1.0 -r 22050 -  -t wav test.wav` programatically on the ESP32? Is there a better way than [`exec()`](https://stackoverflow.com/a/437857)? Would I have to recreate `main()` in my script?
- The above command would then create a WAV-file that I could then play via the ESP32's DAC somehow. Direct output as seen in the tutorial `python termux_beacon.py | python aprs_mod.py -vox -t play -t -` could be achieved by using `echo "KI5TOF>APRS:>hello world!" | micropython aprs_mod.py -vox -t play -t -` Correct? How would I realize that in a Micropython script?

As you can see, I'm at a bit of a loss here. Since the package seems to be exactly what I was looking for, I hope you can help me. 

Thanks, Kurt

**Comment by stephanelsmith** [comment]
You're in luck, I'm actually currently working on the esp32 implementation for the same module. specifically the lilygo t-twr module.  The project will be located here, still in very early stage:
https://github.com/stephanelsmith/micro-twr

This will provide an esp32 integration quite close to what you could use.  Micropython will need encorporate an ESP32 speific PR for everything to work, so I hope you are not in a hurry!

**Comment by stephanelsmith** [comment]
Closing issue, resolved in a different repo.

**Comment by nitricware** [comment]
I'm not sure if I understand that correctly.

The second project is a micropython package to use the SA818 or is it a package to generate APRS, AFSK and transmit that via the SA818?

I'm happy either way!

However, I'm still don't know how to implement your micro-aprs package in existing python code. Will that be explained in the second project?

Thanks for the link to the second project.

If there is anything I could contribute, let me know and I'll try!

**Comment by stephanelsmith** [comment]
In existing python, clone the repo, and in the src folder, try the examples.  They should run without any other requirment. Eg.
```python aprs_mod.py -h```

This project is a command line interface which matches the interface of similiar tools (direwolf and ngmultimon).  Much easier to test and benchmark on cli.  On the flip side, you cannot directly use in a microcontroller without creating your own top level py.  The "core" should all work without modification.

In a real esp32 deployment, you will want to build micropython and "freeze" the py files for best performance.

The main somewhat unknown right now is analog output as I2S to esp32s3 is not a directly supported mode.  There's work that's been done here:
https://github.com/nakhonthai/ESP32APRS_T-TWR/tree/main/doc
https://www.atomic14.com/2024/01/05/esp32-s3-no-pins.html#:~:text=So%2C%20there's%20no%20DAC%20on,and%20use%20an%20analog%20amplifier
But this is the next step.
